# Generated by Django 3.2.3 on 2021-05-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('form 3', 'form 3'), ('form 1', 'form 1'), ('form 2', 'form 2'), ('form 4', 'form 3')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='students/images')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='about.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student_leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='about.student')),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('motto', models.TextField()),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='about.student')),
                ('dep_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.student')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('aims', models.TextField()),
                ('message', models.TextField()),
                ('president', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='prefect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.stream'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.staff'),
        ),
    ]
