# Generated by Django 3.2.3 on 2021-05-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210528_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('form 3', 'form 3'), ('form 4', 'form 4'), ('form 2', 'form 2'), ('form 1', 'form 1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='prefect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.staff'),
        ),
    ]
