# Generated by Django 3.2.3 on 2021-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210528_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adm_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('form 2', 'form 2'), ('form 4', 'form 4'), ('form 1', 'form 1'), ('form 3', 'form 3')], max_length=20),
        ),
    ]
