# Generated by Django 3.2.3 on 2021-05-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210528_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='master',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('form 4', 'form 4'), ('form 1', 'form 1'), ('form 3', 'form 3'), ('form 2', 'form 2')], max_length=20),
        ),
    ]
