# Generated by Django 3.2.3 on 2021-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210528_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department_members',
            new_name='Department_member',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('form 3', 'form 3'), ('form 1', 'form 1'), ('form 2', 'form 2'), ('form 4', 'form 4')], max_length=20),
        ),
    ]
